Adaptions needed for using Photonic3D on the YHD-101
WheresWaldo/Marlin_KLD-LCD pull request #4
Opened 2017-07-22 12:56 UTC by bringho

These changes are proposed to stop the YHD-101 to stall the z-axis motor when Photonic3D tries to do fast manual moves and to increase safety as we should never have to manually move the build platform lower than the z endstop.

2017-07-22 13:01 UTC, bringho commented
I still have not figured out how to select commits, the updated README.md should obliviously not be in here!

2017-07-31 23:09 UTC, WheresWaldo commented
Sorry for the delay, I finally got around to looking this over. Is there a way for you to create a pull request that does not include the updated README.md since that really only applies to your fork and not this source in general.

2017-07-31 23:27 UTC, WheresWaldo reviewed
Making sure this works

2017-07-31 23:29 UTC, WheresWaldo requested changes
Revert to original file

2017-07-31 23:40 UTC, closed without merging

2017-08-01 14:01 UTC, bringho commented
I have poked around a bit, still trying to get more acquainted with github..

I guess the easy way to get this right is to restore most of the original readme in my fork, only adding my changes art the top?

2017-08-01 15:26 UTC, WheresWaldo commented
I don't know if you saw my post on G+ but since I can't figure out all of GITHUB either I duplicated your edits and added them to the 'experimental' branch.

2017-08-01 15:36 UTC, bringho commented
No I did not see the G+ post. I went deeper into github learned how to
revert my commits so I made another pull request.

Off to have my daily G+ read now =)

/ B

2017-08-01 17:26 GMT+02:00 WheresWaldo <notifications@github.com>:

> I don't know if you saw my post on G+ but since I can't figure out all of
> GITHUB either I duplicated your edits and added them to the 'experimental'
> branch.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/WheresWaldo/Marlin_KLD-LCD/pull/4#issuecomment-319405285>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AHKHOGeEqWBbvXEVE4FY9fHXu5-TUgcOks5sT0O_gaJpZM4OgKmg>
> .
>